import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "./components/nav";
import PostsProvider from "./components/posts-container";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pages = [
  {
    id: 1,
    name: "Home",
    href: "/",
  },
  {
    id: 2,
    name: "New",
    href: "/new",
  },
  {
    id: 3,
    name: "Popular",
    href: "/popular",
  },
  {
    id: 4,
    name: "Trending",
    href: "/trending",
  },
  {
    id: 5,
    name: "Categories",
    href: "/categories",
  },
];

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PostsProvider>
          <div className="w-11/12 max-w-[1110px] mx-auto">
            <Nav pages={pages} />
            {children}
          </div>
        </PostsProvider>
      </body>
    </html>
  );
}
